version: '3.7'

services:
  app:
    image: cms
    build: .
    command: ./config/uwsgi/init.sh
    environment:
      PYTHONUNBUFFERED: 1
      DJANGO_ENV: dev
    volumes:
      - .:/app
    ports:
      - 8000:8000
#  nginx:
#    image: nginx
#    ports:
#      - "80:80"
#    volumes:
#      - ./log/nginx:/var/log/nginx
#      - ./config/nginx/app.conf:/etc/nginx/conf.d
#      - ./config/certbot/conf:/etc/letsencrypt
#      - ./config/certbot/www:/var/www/certbot
#    links:
#      - app:app
#  certbot:
#    image: certbot/certbot
#    volumes:
#      - ./config/certbot/conf:/etc/letsencrypt
#      - ./config/certbot/www:/var/www/certbot
