version: '3.7'

services:
  app:
    image: cms
    build: .
    command: ./config/uwsgi/init.sh
    environment:
      PYTHONUNBUFFERED: 1
      DJANGO_ENV: dev
    volumes:
      - .:/app
    expose:
      - "8000"
#  nginx:
#    image: nginx:1.15-alpine
#    ports:
#      - "80:80"
#    volumes:
#      - ./config/nginx:/etc/nginx/conf.d
#      - ./config/certbot/conf:/etc/letsencrypt
#      - ./config/certbot/www:/var/www/certbot
#  certbot:
#    image: certbot/certbot
#    volumes:
#      - ./config/certbot/conf:/etc/letsencrypt
#      - ./config/certbot/www:/var/www/certbot