version: '3.7'

services:
  app:
    image: cms
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    environment:
      PYTHONUNBUFFERED: 1
      DJANGO_ENV: dev
    volumes:
      - .:/app
    ports:
      - 8000:8000
