# Generated by Django 3.1.4 on 2020-12-04 20:01

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliopage',
            name='item',
        ),
        migrations.AddField(
            model_name='portfoliopage',
            name='items',
            field=wagtail.core.fields.StreamField([('item', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('body', wagtail.core.blocks.RichTextBlock(required=False))]))], blank=True),
        ),
    ]
