# Generated by Django 3.1.4 on 2020-12-04 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20201204_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seo',
            name='text',
        ),
        migrations.RemoveField(
            model_name='seo',
            name='url',
        ),
    ]
