# Generated by Django 3.1.4 on 2020-12-04 20:26

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20201204_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='seo',
            name='seo',
            field=wagtail.core.fields.StreamField([('tag', wagtail.core.blocks.RawHTMLBlock(form_classname='full title'))], blank=True),
        ),
    ]
