# Generated by Django 3.1.4 on 2020-12-04 20:29

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_seo_seo'),
    ]

    operations = [
        migrations.AddField(
            model_name='seo',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='seo',
            name='seo',
            field=wagtail.core.fields.StreamField([('tag', wagtail.core.blocks.RawHTMLBlock())], blank=True),
        ),
    ]
